// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Motel.Core.Data;

namespace Motel.Core.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20221018103701___addColumnRoom")]
    partial class __addColumnRoom
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Motel.Core.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("Role")
                        .HasColumnName("role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d99e5848-b4f0-4717-a0aa-5de51df3e1de"),
                            Address = "Cổ Nhuế, Từ Liêm",
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 404, DateTimeKind.Local).AddTicks(9188),
                            Gender = 1,
                            Mail = "trongnhan1110i@gmail.com",
                            Name = "Phạm Trọng Nhân",
                            Password = "T24UgcZyY5d5T538cm2QRc80DLB/e79sk97fjiJDzJw=",
                            Phone = "0775331777",
                            Role = 0,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 405, DateTimeKind.Local).AddTicks(5972)
                        });
                });

            modelBuilder.Entity("Motel.Core.Entities.BoardingHouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("EndDatePayment")
                        .HasColumnType("int");

                    b.Property<bool?>("IsNotLimitTime")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSelfPayment")
                        .HasColumnType("bit");

                    b.Property<int>("Months")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("StartDatePayment")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("BoardingHouses");
                });

            modelBuilder.Entity("Motel.Core.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Motel.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("BackIdentityPath")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Career")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FontIdentityPath")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationCitizen")
                        .HasColumnType("nvarchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Motel.Core.Entities.Fitment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<bool>("IsCanUse")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<double>("RecoupPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Fitments");
                });

            modelBuilder.Entity("Motel.Core.Entities.FitmentInRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FitmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FitmentId");

                    b.HasIndex("RoomId");

                    b.ToTable("FitmentInRooms");
                });

            modelBuilder.Entity("Motel.Core.Entities.Provide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DefaultPrice")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Provides");

                    b.HasData(
                        new
                        {
                            Id = new Guid("804679b7-da23-449b-9935-1cd0a92cb6a8"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(3610),
                            DefaultPrice = 4000.0,
                            Name = "Tiền điện",
                            Type = 1,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(3630)
                        },
                        new
                        {
                            Id = new Guid("89506908-1608-48d4-bdec-82d07c1fbf75"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4234),
                            DefaultPrice = 100000.0,
                            Name = "Tiền nước",
                            Type = 1,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4238)
                        },
                        new
                        {
                            Id = new Guid("ad43f340-75b4-4f45-a44d-787e02fc8411"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4264),
                            DefaultPrice = 50000.0,
                            Name = "Gửi Xe máy",
                            Type = 0,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4265)
                        },
                        new
                        {
                            Id = new Guid("1def1838-9603-4d13-8955-f74d0256d653"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4267),
                            DefaultPrice = 0.0,
                            Name = "Tiền xe đạp",
                            Type = 0,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4268)
                        },
                        new
                        {
                            Id = new Guid("32780181-97ad-4e3a-a3ee-54991e78b9a3"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4270),
                            DefaultPrice = 100000.0,
                            Name = "Tiền xe điện",
                            Type = 0,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4270)
                        },
                        new
                        {
                            Id = new Guid("1e7d6826-6efd-4861-a586-a7bf98b190bd"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4272),
                            DefaultPrice = 50000.0,
                            Name = "Internet",
                            Type = 0,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4273)
                        },
                        new
                        {
                            Id = new Guid("38d55efd-0af8-49c4-bc67-149265f12e7d"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4274),
                            DefaultPrice = 10000.0,
                            Name = "Bảo vệ",
                            Type = 0,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4275)
                        },
                        new
                        {
                            Id = new Guid("d79fd593-bb1a-46a7-844c-797729d73793"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4276),
                            DefaultPrice = 0.0,
                            Name = "Máy giặt",
                            Type = 0,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4277)
                        },
                        new
                        {
                            Id = new Guid("c4a75521-88f5-458f-b460-7baf192ed99c"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4285),
                            DefaultPrice = 0.0,
                            Name = "Truyền hình cáp",
                            Type = 0,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4285)
                        },
                        new
                        {
                            Id = new Guid("8288f7a7-02b6-4623-bfdb-ccd18b9e90d2"),
                            CreatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4287),
                            DefaultPrice = 50000.0,
                            Name = "Thang máy",
                            Type = 0,
                            UpdatedAt = new DateTime(2022, 10, 18, 17, 37, 1, 406, DateTimeKind.Local).AddTicks(4287)
                        });
                });

            modelBuilder.Entity("Motel.Core.Entities.ProvideInBoardingHouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardingHouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("ProvideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoardingHouseId");

                    b.HasIndex("ProvideId");

                    b.ToTable("ServiceInBoardingHouses");
                });

            modelBuilder.Entity("Motel.Core.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardingHouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSelfContainer")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxHuman")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoardingHouseId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Motel.Core.Entities.RoomDeposited", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<double>("DespositedValue")
                        .HasColumnType("float");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomDepositeds");
                });

            modelBuilder.Entity("Motel.Core.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Motel.Core.Entities.AppUser", b =>
                {
                    b.HasOne("Motel.Core.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("Motel.Core.Entities.BoardingHouse", b =>
                {
                    b.HasOne("Motel.Core.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");
                });

            modelBuilder.Entity("Motel.Core.Entities.Customer", b =>
                {
                    b.HasOne("Motel.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("Motel.Core.Entities.FitmentInRoom", b =>
                {
                    b.HasOne("Motel.Core.Entities.Fitment", "Fitment")
                        .WithMany()
                        .HasForeignKey("FitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motel.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Motel.Core.Entities.ProvideInBoardingHouse", b =>
                {
                    b.HasOne("Motel.Core.Entities.BoardingHouse", "BoardingHouse")
                        .WithMany()
                        .HasForeignKey("BoardingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Motel.Core.Entities.Provide", "Provide")
                        .WithMany()
                        .HasForeignKey("ProvideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Motel.Core.Entities.Room", b =>
                {
                    b.HasOne("Motel.Core.Entities.BoardingHouse", "BoardingHouse")
                        .WithMany()
                        .HasForeignKey("BoardingHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Motel.Core.Entities.RoomDeposited", b =>
                {
                    b.HasOne("Motel.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Motel.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("Motel.Core.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
